const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET

const CLOUD_NAME = process.env.CLOUD_NAME
const PRESET = process.env.PRESET

export default {
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUD_NAME,
  PRESET
}
